import type { LernSession, Klausur, Todo, PomodoroSession } from "./types";

// ─── Lernplan Dummy Data ────────────────────────────────────────────
export const DUMMY_SESSIONS: LernSession[] = [
  {
    id: "s1",
    title: "StrafR – Revision & Berufung",
    subject: "StrafR",
    date: "2026-06-24T09:00:00",
    duration: 2,
    status: ["Skript geschrieben", "Hemmer"],
    priority: "High",
    examensrelevanz: [5],
    completed: false,
    wiederholungen: 3,
    klausurenIds: ["k1"],
    pomodoroIds: ["p1", "p2"],
    todoIds: [],
    parentId: null,
    subIds: [],
    unterlagen: ["Hemmer Skript.pdf"],
    lernTodos: "Prüfungsschema nochmals durchgehen\nFallgruppen bei §§ 312 ff. StPO",
  },
  {
    id: "s2",
    title: "ZPO – Berufung im Zivilrecht",
    subject: "ZPO",
    date: "2026-06-24T14:00:00",
    duration: 1.5,
    status: ["Skript geschrieben"],
    priority: "Medium",
    examensrelevanz: [4],
    completed: false,
    wiederholungen: 1,
    klausurenIds: ["k2"],
    pomodoroIds: [],
    todoIds: ["t1"],
    parentId: null,
    subIds: ["s3"],
    unterlagen: [],
    lernTodos: "",
  },
  {
    id: "s3",
    title: "ZPO III – Besondere Verfahren",
    subject: "ZPO III",
    date: "2026-06-25T10:00:00",
    duration: 2,
    status: ["offen"],
    priority: "Low",
    examensrelevanz: [3],
    completed: false,
    wiederholungen: 0,
    klausurenIds: [],
    pomodoroIds: [],
    todoIds: [],
    parentId: "s2",
    subIds: [],
    unterlagen: [],
    lernTodos: "",
  },
  {
    id: "s4",
    title: "VwR – Anfechtungsklage",
    subject: "VwR",
    date: "2026-06-25T08:00:00",
    duration: 3,
    status: ["Skript geschrieben", "Ankis"],
    priority: "High",
    examensrelevanz: [5],
    completed: false,
    wiederholungen: 2,
    klausurenIds: ["k3"],
    pomodoroIds: ["p3"],
    todoIds: [],
    parentId: null,
    subIds: [],
    unterlagen: ["VwR Skript.pdf", "VwGO Überblick.pdf"],
    lernTodos: "Zulässigkeit vollständig wiederholen",
  },
  {
    id: "s5",
    title: "ZivR – Schadensersatz",
    subject: "ZivR",
    date: "2026-06-26T11:00:00",
    duration: 2.5,
    status: ["Skript geschrieben", "Hemmer", "Ankis"],
    priority: "Medium",
    examensrelevanz: [4],
    completed: false,
    wiederholungen: 4,
    klausurenIds: [],
    pomodoroIds: [],
    todoIds: ["t2"],
    parentId: null,
    subIds: [],
    unterlagen: [],
    lernTodos: "",
  },
  {
    id: "s6",
    title: "StPO – Ermittlungsverfahren",
    subject: "StPO",
    date: null,
    duration: 2,
    status: ["offen"],
    priority: "Medium",
    examensrelevanz: [4],
    completed: false,
    wiederholungen: 0,
    klausurenIds: ["k1"],
    pomodoroIds: [],
    todoIds: [],
    parentId: null,
    subIds: [],
    unterlagen: [],
    lernTodos: "",
  },
  {
    id: "s7",
    title: "VwGO – Vorläufiger Rechtsschutz",
    subject: "VwGO",
    date: null,
    duration: 1.5,
    status: ["offen"],
    priority: "High",
    examensrelevanz: [5],
    completed: false,
    wiederholungen: 0,
    klausurenIds: ["k3"],
    pomodoroIds: [],
    todoIds: [],
    parentId: null,
    subIds: [],
    unterlagen: [],
    lernTodos: "",
  },
  {
    id: "s8",
    title: "ZivR – Deliktsrecht",
    subject: "ZivR",
    date: "2026-06-27T09:00:00",
    duration: 2,
    status: ["Skript geschrieben"],
    priority: "Medium",
    examensrelevanz: [3],
    completed: false,
    wiederholungen: 1,
    klausurenIds: [],
    pomodoroIds: [],
    todoIds: [],
    parentId: null,
    subIds: [],
    unterlagen: [],
    lernTodos: "",
  },
];

// ─── Klausuren Dummy Data ───────────────────────────────────────────
export const DUMMY_KLAUSUREN: Klausur[] = [
  {
    id: "k1",
    title: "StrafR – Berufung/Revision",
    fach: "StrafR",
    ort: "Hemmer",
    status: "zu schreiben",
    ausgabeDatum: "2026-06-20",
    schreibDatum: "2026-06-27",
    abgabeDatum: "2026-07-04",
    nachbesprechung: "2026-07-11",
    nachbearbeiten: "2026-07-14",
    note: "",
    problemuebersicht: "",
    lernplanIds: ["s1", "s6"],
  },
  {
    id: "k2",
    title: "ZPO – Berufungsrecht",
    fach: "ZPO",
    ort: "AG",
    status: "zu schreiben",
    ausgabeDatum: "2026-07-01",
    schreibDatum: "2026-07-04",
    abgabeDatum: "2026-07-11",
    nachbesprechung: "2026-07-18",
    nachbearbeiten: null,
    note: "",
    problemuebersicht: "",
    lernplanIds: ["s2"],
  },
  {
    id: "k3",
    title: "VwR – Anfechtungsklage & einstweiliger RS",
    fach: "VwR",
    ort: "AssK",
    status: "offen",
    ausgabeDatum: null,
    schreibDatum: "2026-07-18",
    abgabeDatum: "2026-07-25",
    nachbesprechung: null,
    nachbearbeiten: null,
    note: "",
    problemuebersicht: "",
    lernplanIds: ["s4", "s7"],
  },
  {
    id: "k4",
    title: "ZivR – Schadensersatz & Deliktsrecht",
    fach: "ZivR",
    ort: "Hemmer",
    status: "nachzuarbeiten",
    ausgabeDatum: "2026-06-01",
    schreibDatum: "2026-06-06",
    abgabeDatum: "2026-06-13",
    nachbesprechung: "2026-06-20",
    nachbearbeiten: "2026-07-01",
    note: "9 Punkte",
    problemuebersicht: "Probleme bei § 831 BGB",
    lernplanIds: ["s5"],
  },
];

// ─── To-Dos Dummy Data ──────────────────────────────────────────────
export const DUMMY_TODOS: Todo[] = [
  {
    id: "t1",
    name: "ZPO Karteikarten Berufung fertigstellen",
    date: "2026-06-24",
    completed: false,
    kategorie: "KK",
    kat: "ZPO",
    lernplanIds: ["s2"],
  },
  {
    id: "t2",
    name: "ZivR AG-Protokoll durcharbeiten",
    date: "2026-06-25",
    completed: false,
    kategorie: "AG",
    kat: "ZivR",
    lernplanIds: ["s5"],
  },
  {
    id: "t3",
    name: "StrafR Hemmer Skript kaufen",
    date: "2026-06-23",
    completed: false,
    kategorie: "Lernen",
    kat: "StrafR",
    lernplanIds: ["s1"],
  },
  {
    id: "t4",
    name: "VwR AssK Unterlagen einreichen",
    date: "2026-06-26",
    completed: false,
    kategorie: "AssK",
    kat: "VwR",
    lernplanIds: [],
  },
  {
    id: "t5",
    name: "Pomodoro-Sessions für KW 27 planen",
    date: "2026-06-28",
    completed: false,
    kategorie: "Lernen",
    kat: null,
    lernplanIds: [],
  },
  {
    id: "t6",
    name: "StPO Ankis Fortschritt überprüfen",
    date: "2026-06-27",
    completed: true,
    kategorie: "KK",
    kat: "StPO",
    lernplanIds: ["s6"],
  },
];

// ─── Pomodoro Dummy Data ────────────────────────────────────────────
export const DUMMY_POMODOROS: PomodoroSession[] = [
  {
    id: "p1",
    title: "StrafR Revision – Block 1",
    start: "2026-06-23T09:00:00",
    ende: "2026-06-23T09:25:00",
    dauerMin: 25,
    typ: "Pomodoro",
    lerneinheitId: "s1",
  },
  {
    id: "p2",
    title: "StrafR Revision – Block 2",
    start: "2026-06-23T09:30:00",
    ende: "2026-06-23T09:55:00",
    dauerMin: 25,
    typ: "Pomodoro",
    lerneinheitId: "s1",
  },
  {
    id: "p3",
    title: "VwR Anfechtung – Block 1",
    start: "2026-06-22T10:00:00",
    ende: "2026-06-22T10:25:00",
    dauerMin: 25,
    typ: "Pomodoro",
    lerneinheitId: "s4",
  },
];
