/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as StaatsexamenRouteImport } from './routes/staatsexamen'
import { Route as FokusRouteImport } from './routes/fokus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiNotionTodosRouteImport } from './routes/api/notion/todos'
import { Route as ApiNotionSessionsRouteImport } from './routes/api/notion/sessions'
import { Route as ApiNotionKlausurenRouteImport } from './routes/api/notion/klausuren'
import { Route as ApiNotionHealthRouteImport } from './routes/api/notion/health'
import { Route as ApiGoogleConfigRouteImport } from './routes/api/google/config'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const StaatsexamenRoute = StaatsexamenRouteImport.update({
  id: '/staatsexamen',
  path: '/staatsexamen',
  getParentRoute: () => rootRouteImport,
} as any)
const FokusRoute = FokusRouteImport.update({
  id: '/fokus',
  path: '/fokus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotionTodosRoute = ApiNotionTodosRouteImport.update({
  id: '/api/notion/todos',
  path: '/api/notion/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotionSessionsRoute = ApiNotionSessionsRouteImport.update({
  id: '/api/notion/sessions',
  path: '/api/notion/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotionKlausurenRoute = ApiNotionKlausurenRouteImport.update({
  id: '/api/notion/klausuren',
  path: '/api/notion/klausuren',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotionHealthRoute = ApiNotionHealthRouteImport.update({
  id: '/api/notion/health',
  path: '/api/notion/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleConfigRoute = ApiGoogleConfigRouteImport.update({
  id: '/api/google/config',
  path: '/api/google/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fokus': typeof FokusRoute
  '/staatsexamen': typeof StaatsexamenRoute
  '/todos': typeof TodosRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/google/config': typeof ApiGoogleConfigRoute
  '/api/notion/health': typeof ApiNotionHealthRoute
  '/api/notion/klausuren': typeof ApiNotionKlausurenRoute
  '/api/notion/sessions': typeof ApiNotionSessionsRoute
  '/api/notion/todos': typeof ApiNotionTodosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fokus': typeof FokusRoute
  '/staatsexamen': typeof StaatsexamenRoute
  '/todos': typeof TodosRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/google/config': typeof ApiGoogleConfigRoute
  '/api/notion/health': typeof ApiNotionHealthRoute
  '/api/notion/klausuren': typeof ApiNotionKlausurenRoute
  '/api/notion/sessions': typeof ApiNotionSessionsRoute
  '/api/notion/todos': typeof ApiNotionTodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fokus': typeof FokusRoute
  '/staatsexamen': typeof StaatsexamenRoute
  '/todos': typeof TodosRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/google/config': typeof ApiGoogleConfigRoute
  '/api/notion/health': typeof ApiNotionHealthRoute
  '/api/notion/klausuren': typeof ApiNotionKlausurenRoute
  '/api/notion/sessions': typeof ApiNotionSessionsRoute
  '/api/notion/todos': typeof ApiNotionTodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fokus'
    | '/staatsexamen'
    | '/todos'
    | '/api/ai/chat'
    | '/api/google/config'
    | '/api/notion/health'
    | '/api/notion/klausuren'
    | '/api/notion/sessions'
    | '/api/notion/todos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fokus'
    | '/staatsexamen'
    | '/todos'
    | '/api/ai/chat'
    | '/api/google/config'
    | '/api/notion/health'
    | '/api/notion/klausuren'
    | '/api/notion/sessions'
    | '/api/notion/todos'
  id:
    | '__root__'
    | '/'
    | '/fokus'
    | '/staatsexamen'
    | '/todos'
    | '/api/ai/chat'
    | '/api/google/config'
    | '/api/notion/health'
    | '/api/notion/klausuren'
    | '/api/notion/sessions'
    | '/api/notion/todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FokusRoute: typeof FokusRoute
  StaatsexamenRoute: typeof StaatsexamenRoute
  TodosRoute: typeof TodosRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiGoogleConfigRoute: typeof ApiGoogleConfigRoute
  ApiNotionHealthRoute: typeof ApiNotionHealthRoute
  ApiNotionKlausurenRoute: typeof ApiNotionKlausurenRoute
  ApiNotionSessionsRoute: typeof ApiNotionSessionsRoute
  ApiNotionTodosRoute: typeof ApiNotionTodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staatsexamen': {
      id: '/staatsexamen'
      path: '/staatsexamen'
      fullPath: '/staatsexamen'
      preLoaderRoute: typeof StaatsexamenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fokus': {
      id: '/fokus'
      path: '/fokus'
      fullPath: '/fokus'
      preLoaderRoute: typeof FokusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notion/todos': {
      id: '/api/notion/todos'
      path: '/api/notion/todos'
      fullPath: '/api/notion/todos'
      preLoaderRoute: typeof ApiNotionTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notion/sessions': {
      id: '/api/notion/sessions'
      path: '/api/notion/sessions'
      fullPath: '/api/notion/sessions'
      preLoaderRoute: typeof ApiNotionSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notion/klausuren': {
      id: '/api/notion/klausuren'
      path: '/api/notion/klausuren'
      fullPath: '/api/notion/klausuren'
      preLoaderRoute: typeof ApiNotionKlausurenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notion/health': {
      id: '/api/notion/health'
      path: '/api/notion/health'
      fullPath: '/api/notion/health'
      preLoaderRoute: typeof ApiNotionHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/config': {
      id: '/api/google/config'
      path: '/api/google/config'
      fullPath: '/api/google/config'
      preLoaderRoute: typeof ApiGoogleConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FokusRoute: FokusRoute,
  StaatsexamenRoute: StaatsexamenRoute,
  TodosRoute: TodosRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiGoogleConfigRoute: ApiGoogleConfigRoute,
  ApiNotionHealthRoute: ApiNotionHealthRoute,
  ApiNotionKlausurenRoute: ApiNotionKlausurenRoute,
  ApiNotionSessionsRoute: ApiNotionSessionsRoute,
  ApiNotionTodosRoute: ApiNotionTodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
